jobs:
  include:
  - script: echo "no tests yet -- success"

before_deploy:
- openssl aes-256-cbc -K $encrypted_3151e9772873_key -iv $encrypted_3151e9772873_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa.pem
- ssh-add /tmp/deploy_rsa.pem

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -a --delete-after --quiet $TRAVIS_BUILD_DIR/wp-content/themes/flueba tom@tmbe.me:www/flueba/wp-content/themes/flueba
  on:
    branch: redesign-2018
